---
- hosts: all
  become: yes
  roles:
    - {role: ./roles/ansible-role-drachtio, when: install_drachtio|bool}
    - {role: ./roles/ansible-role-fail2ban-drachtio, when: install_drachtio_fail2ban|bool}
    - {role: ./roles/ansible-role-fsmrf, when: install_freeswitch|bool}
    - {role: ./roles/ansible-role-rtpengine, when: install_rtpengine|bool}
    - {role: ./roles/ansible-role-nodejs, when: install_nodejs|bool}
